name: Deploy Firebase App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      env:
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      run: npm run build

    - name: Deploy to Firebase
      env:
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      run: firebase deploy --token ${{ secrets.FIREBASE_API_KEY }}
